apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
spec:
  volumeName: prom-tsdb-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
