apiVersion: v1
kind: PersistentVolume
metadata:
  name: pi-dnsmasq-pv
spec:
  capacity:
   storage: 1Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/pi-dnsmasq"
