apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-dnsmasq-pvc
spec:
  volumeName: pi-dnsmasq-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
