apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-blackbox-dep
  labels:
    app: prom-blackbox-dep
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-blackbox-dep
  template:
    metadata:
      labels:
        app: prom-blackbox-dep
    spec:
      containers:
      - name: black-box
        image: quay.io/prometheus/blackbox-exporter:master
        args:
        - --config.file=/config/blackbox.yml
        ports:
        - containerPort: 9115
        volumeMounts:
          - name: blackbox-cm
            mountPath: /config
            subPath: test
      volumes:
      - name: blackbox-cm
        configMap:
          name: blackbox-cm

