apiVersion: v1
kind: Service
metadata:
  name: blackbox-svc
spec:
  type: LoadBalancer
  selector:
    app: prom-blackbox-dep
  ports:
    - protocol: TCP
      name: web
      port: 9115
      targetPort: 9115
