apiVersion: v1
kind: PersistentVolume
metadata:
  name: graf-pv
  namespace: monitoring
spec:
  capacity:
   storage: 2Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/graf-pv"
