apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc
  namespace: monitoring
spec:
  volumeName: graf-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
