apiVersion: v1
kind: Service
metadata:
  name: my-traefik-dashboard
  annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9100'
        prometheus.io/path: '/metrics'
spec:
  selector:
    app.kubernetes.io/name: traefik
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
