apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9100'
        prometheus.io/path: '/metrics'
spec:
  selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
  ports:
  - name: node-exporter
    port: 9100
    targetPort: 9100
