name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
  TF_VAR_GUESTWIFIPASS: ${{ secrets.TF_VAR_GUESTWIFIPASS }}
  TF_VAR_GUESTWIFISSID: ${{ secrets.TF_VAR_GUESTWIFISSID }}
  TF_VAR_HOMEWIFIPASS: ${{ secrets.TF_VAR_HOMEWIFIPASS }}
  TF_VAR_HOMEWIFISSID: ${{ secrets.TF_VAR_HOMEWIFISSID }}
  UNIFI_API: ${{ secrets.UNIFI_API }}
  UNIFI_USERNAME: ${{ secrets.UNIFI_USERNAME }}
  UNIFI_PASSWORD: ${{ secrets.UNIFI_PASSWORD }}
      

jobs:
  terraform:
    runs-on: self-hosted
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan
